### ISSUE TITLE
Running 2 RTX 4070 Ti qwen2.5-coder:14b-instruct-q8_0 SLOWWW

### ISSUE THREAD

**Issue by RBucci** [stackblitz-labs/bolt.diy#557] opened 2024-12-05 19:29 UTC
### Describe the bug

On prompt entry, the model that should be articulate and fast (on Open WebUI it's lightning fast) it takes forever for bolt to complete a single sentence. Why could that be? It seems like it's trying to load 2 models at the same time.

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/1

### Steps to reproduce

1. Install Bolt through Pinokio
2. Configure LAN Ollama Server
3. Enter prompt
4. Wait forever...

### Expected behavior

Should be very fast

### Platform

- OS: Windows 10 - Laptop
- Ollama Server: Ubuntu Server 24.04 - Dual Xeon - Dual RTX 4070 Ti - 128 GB RAM
- Browser: Chrome
- Version: 131.0.6778.86

### Provider Used

Ollama

### Model Used

qwen2.5-coder:14b-instruct-q8_0

**Comment by aliasfoxkde** [comment] 2024-12-05 20:56
Using Ollama directly, how does it work? Do you know how many tokens per second?

**Comment by RBucci** [comment] 2024-12-06 03:37
I'm quite new to AI, I'd be lying if I gave you a number. Bolt recognized the remote ollama and their models (7b and 14b) but as far as tokens per second, I don't really know what you mean by that.

**Comment by Yota73** [comment] 2024-12-06 16:20
It seems like my issue. Try to use a small model like qwen2.5-coder 7b (4.7GB), if it runs normally you are in my case:

https://github.com/coleam00/bolt.new-any-llm/issues/556

kekePower suggests that I have two bolt instances but I haven't found where the second one is launched yet

**Comment by RBucci** [comment] 2024-12-06 16:35
Still slower than it should be. It might have something to do with default
CTX.

**Comment by kekePower** [comment] 2024-12-06 20:03
I just tried running hermes3:8b which is about 4.7GB on my 3070 8GB and it still uses the CPU. The same model works great and is really fast in Lobe Chat..

**Comment by RBucci** [comment] 2024-12-06 21:38
> I just tried running hermes3:8b which is about 4.7GB on my 3070 8GB and it still uses the CPU. The same model works great and is really fast in Lobe Chat..

Whats your environment? Are you running on Linux or Windows? Could be double load as well..

**Comment by kekePower** [comment] 2024-12-07 06:44
> > I just tried running hermes3:8b which is about 4.7GB on my 3070 8GB and it still uses the CPU. The same model works great and is really fast in Lobe Chat..
> 
> Whats your environment? Are you running on Linux or Windows? Could be double load as well..

I'm running Linux and run oTToDev locally(localhost), not in docker. Ollama is on another machine.

**Comment by RBucci** [comment] 2024-12-07 08:35
> > > I just tried running hermes3:8b which is about 4.7GB on my 3070 8GB and it still uses the CPU. The same model works great and is really fast in Lobe Chat..
> > 
> > 
> > Whats your environment? Are you running on Linux or Windows? Could be double load as well..
> 
> I'm running Linux and run oTToDev locally(localhost), not in docker. Ollama is on another machine.

It's almost as if it requests two or more instances of the model..
However, try the following commands on console:

`systemctl stop ollama`
`sudo rmmod nvidia_uvm`
`sudo modprobe nvidia_uvm`
`systemctl start ollama`

It helped me with ollama not using GPU at times.

**Comment by thecodacus** [comment] 2024-12-07 17:02
did you try to run in terminal and there its running fast?

**Comment by RBucci** [comment] 2024-12-07 18:46
Ollama is responding blazing fast in terminal, yes.

**Comment by thecodacus** [comment] 2024-12-07 19:53
okay I saw another issue similar to this.. 
bolt uses 4k tokens for system prompt. that takes alot of memory, as memory user exponentially grows along with context size. that might be the reason

**Comment by thecodacus** [comment] 2024-12-12 20:07
closing, will reopen if the issue is not related to high context usage

**Closed by thecodacus** 2024-12-12 20:07 UTC
